# Generated by Django 3.0.7 on 2020-06-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=200)),
                ('placa', models.CharField(max_length=8)),
                ('cep', models.CharField(max_length=10)),
                ('curso', models.CharField(choices=[('cc', 'Ciências da computação'), ('ds', 'Design')], max_length=25)),
            ],
        ),
    ]
